packetbeat:
    version: 0.5.0

    deb:
        arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'i386' }}"

    rpm:
        arch: "{{ 'x86_64' if ansible_architecture == 'x86_64' else 'i686' }}"

    config:
        interface:
            device: "any"
        output:
            elasticsearch:
                enabled: "false"
                host: ""
                port: 9200
                save_topology: "false"
            redis:
                enabled: "true"
                host: "{{ aggregator_bind_ip }}"
                port: 6380
                save_topology: "true"

packetbeat_protocols:
    http:
        enabled: true
        ports:
            - 80
            - 8080
    mysql:
        enabled: true
        ports:
            - 3306
    pgsql:
        enabled: true
        ports:
            - 5432
    redis:
        enabled: true
        ports:
            - 6379

packetbeat_processes:
    mysqld:
        enabled: true
        cmdline_grep: "mysqld"
    pgsql:
        enabled: true
        cmdline_grep: "postgres"
    nginx:
        enabled: true
        cmdline_grep: "nginx"
    redis:
        enabled: true
        cmdline_grep: "redis"

# Find aggregator's IP address from the inventory vars
aggregator_bind_iface: "{{ hostvars[groups['aggregator'][0]].get('main_iface', 'eth0') }}"
aggregator_bind_ip: "{{ hostvars[groups['aggregator'][0]]['ansible_' + aggregator_bind_iface ].ipv4.address }}"

